[package]
name = "quantum-link-macros"
version = "0.1.0"
edition = "2021"
homepage.workspace = true

[dependencies]
#foundation-api = { workspace = true }
quote = "^1"
syn = { version = "^2.0.5", features = ["full", "extra-traits"] }
proc-macro2 = "1"

[lib]
proc-macro = true